# Generated by Django 5.0 on 2024-01-04 20:19

import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dob', models.DateField(help_text='Date of birth')),
                ('profile_img', models.ImageField(upload_to='base/author/img')),
                ('email', models.EmailField(max_length=254)),
                ('primary_phone_number', models.CharField(max_length=255)),
                ('secondary_phone_number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('facebook', models.URLField(blank=True, max_length=255)),
                ('twitter_x', models.URLField(blank=True, max_length=255)),
                ('instagram', models.URLField(blank=True, max_length=255)),
                ('linkedin', models.URLField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Author',
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(upload_to='base/site/img')),
                ('site_title', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, help_text="In a few words describe what this site about e.g. 'Just another portfolio site'", max_length=255)),
                ('site_icon', easy_thumbnails.fields.ThumbnailerImageField(help_text='Site Icons are what you see in browser tabs, bookmark bars, and within the PWA mobile apps. Site Icons should be square and at least 512 x 512 pixels.', upload_to='base/site/img')),
                ('theme_color', models.CharField(max_length=255)),
                ('manifest', models.FileField(upload_to='base/site')),
            ],
            options={
                'verbose_name_plural': 'Site Information',
                'db_table': 'site',
            },
        ),
    ]
